#!/usr/bin/env python
# -*- coding: utf-8 -*-

import tracery
from tracery.modifiers import base_english

rules = {
  'entry': '#template#',
  'template': [
    '#beg##end#!',
    '#adjpl.capitalize# män #medutan# minsta antydan till #subj#!',
    'Olika sorters #subj#!',
    '#namn.capitalize# #aktivitet# i #plats#!',
    '#adjpl.capitalize# #sortpl# #aktivitet# i #plats#!',
    'Vad gör #namn# i #plats#!?',
    'VM i #subst# i #plats#!',
    '#subj.capitalize#ens makt!',
    'Men #namn#!',
    '#namn.capitalize# #aktivitet#!',
    '#namn.capitalize#arnas #tid#!',
    'Pappa vill ha #mat#!',
    'Kom igen nu alla som gillar #slumpen#, #slumpen# och #adjpl# #slumpen#!',
    'Alla som gillar #slumpen# säg HEJ!',
    'Hur mår #namn# egentligen?!',
    '#slumpen.capitalize# HYPE!',
    '#dricka.capitalize#-skål!',
    '#adjpl.capitalize# #namn.s# nya #slumpen#!',
    '#subj.capitalize# i #namn.s# mage!',
    'Vem vill åka #fordon# med #adjpl# #namn# till #plats#?',
    'Jag måste ifrågasätta! #slumpen#!?',
    'Gå och lägg dig #namn#!',
  ],
  'sortpl': [
    'män',
    'kvinnor',
    'ungdomar',
    'katter',
  ],
  'aktivitet': [
    'har #akomma#',
    'äter #mat#',
    'dricker #dricka#',
    'dansar Macarena',
    'köper en ny bil',
    'köper jultidningar',
  ],
  'tid': [
    'afton',
    'kväll',
    'morgon',
    'lunchtid',
  ],
  'subj': [
    'svett',
    'knäproblem',
    'fluor',
    'majs',
    'staniolpapper',
    'karbonpapper',
    'fax',
    'froskas',
    'lekamen',
    'papphus',
  ],
  'akomma': [
    'SARS',
    'brock',
    'streptokocker',
    'karies',
  ],
  'medutan': [ 'med', 'utan' ],
  'adjpl': [ # Adjektiv plural
    'mustiga',
    'svullna',
    'svettiga',
    'vidriga',
    'skäggiga',
    'spanska',
    'koreanska',
    'finska',
    'övertända',
  ],
  'subst': [
    'krabbor',
    'papphus',
    '#subj#',
  ],
  'mat': [
    'MumsMums',
    'Gifflar',
    'majs',
    'selleri',
    'guldnougat',
    'skogaholmslimpa',
    'Cream Sormonium',
    'rabarberblast',
    'protein',
    'havrefras',
    'sprödbakad torsk',
    'svultron',
    '#subj#',
  ],
  'dricka': [
    'Fernet',
    'Powerking',
    'Pepsi max',
  ],
  'fordon': [
    'fernetbuss',
    'traktor',
    'finsk bil',
    'slambil',
    'truck',
  ],
  'namn': [
    '#beg##end# #beg##end#',
    '#beg##end# von #beg##end#',
    'du',
    'Mario',
    'Daniel',
    'Anders Glennmark',
    'Niclas Strömstedt',
    'Orup',
    'Lotta Engberg',
    'Bel-air',
    'Lasse Kroner',
    'Gunde Svan',
    'Janne Boklöv',
    'Fritjof Konkas',
    'Salongo Sali',
    'Sten Frisk',
    'Klimax',
    'Ingvar Oldsberg',
    '#janprefix#-Jan',
    '#janprefix#-Janne',
    '#kennetprefix#-Kennet',
    'Båtsman',
    'Schenkmanis',
    'Triple-n-touch',
    'Moses',
    'Ulf Elfving',
    'Christer Glenning',
    'Phil Spadman',
    'Mossern',
    'Bengt Bedrup',
  ],
  'slumpen': ['#subj#', '#mat#', '#dricka', '#namn#'],
  'kennetprefix': [
    'Kalas',
    'Fluor',
    'Bäver',
    'Yoga',
    'Kokos',
    'Hammar',
    'Kartoffel',
  ],
  'janprefix': [
    'Spenat',
    'Kulan',
    'Snabel',
    'Kulan Snabel-',
    'Lakrits',
    'Svullen',
    'Laktos',
    'Ångest',
    'Knas',
  ],
  'beg': [
    'Svult',
    'Rult',
    'Skvätt',
    'Svett',
    'Skinn',
    'Lak',
    'Sklu',
    'Skägg',
    'Plusk',
  ],
  'end': [
    'von',
    'ron',
    'manis',
    'biff',
    'ling',
    'sal',
    'uge',
    've',
    'be',
    'el',
    'isal',
  ],
  'plats': [
    'bastun',
    'Hällresand',
    'Korea',
    'Spanien',
    'Helsingland',
    'Skövde',
    '#plats1##plats2##plats3#',
  ],
  'plats1': [
    'Häll',
    'Hels',
    'Sunn',
    'Hels',
    'Kal',
    'Mal',
  ],
  'plats2': [
    've',
    're',
    'sing',
  ],
  'plats3': [
    'sand',
    'sund',
    'borg',
    'holm',
    'köping',
  ]
}

def svultron():
	grammar = tracery.Grammar(rules)
	grammar.add_modifiers(base_english)
	return grammar.flatten("#template#")
